eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/

server:
  port: 5555
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign-service
    api-b:
      path: /api-b/**
      serviceId: eurekaClient-service
  retryable: false