#<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
spring:
  application:
    name: thymeleaf-service
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  thymeleaf:
    #设置模板编码，默认值是HTML5，但是过于严格，所以改为LEGACYHTML5，需要导入nekohtml包
    mode: LEGACYHTML5
    #启动thymeleaf热部署
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    # 启用MVC Thymeleaf视图分辨率
    enabled: true
    excluded-view-names:
    # 在构建URL时预先查看名称的前缀
    prefix: classpath:/templates/
    # 构建URL时附加查看名称的后缀
    suffix: .html
    # 链中模板解析器的顺序
    #template-resolver-order:
    # 可以解析的视图名称的逗号分隔列表
    #view-names:
#thymeleaf end