server:
  port: 9898

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/
logging:
  level: info

#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG




