server:
  port: 9899

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/

#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG

logging:
  level: info
