server:
  port: 9878

spring:
  application:
    name: mybatis-springboot
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true
    name: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/