server:
  port: 9878

spring:
  application:
    name: activiti-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    name: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    activiti:
        check-process-definitions: true
        database-schema-update: true
        process-definition-location-prefix: classpath:/processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
        history-level: full
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/