#发现6666是谷歌的非安全端口，所以所有端口改成9开头，四位的，防止因为使用到非安全端口，导致无法使用
server:
  port: 9880

spring:
  application:
    name: feign-service
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/

#因为feign默认时间是1s，所以最好设置下超时时间
#请求处理的超时时间
ribbon:
  ReadTimeout: 12000
#请求连接的超时时间
  ConnectTimeout: 12000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

#Hystrix的超时时间需要大于Ribbon的超时时间，否则Hystrix命令超时后，该命令直接熔断
#重试机制就没有任何意义了
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000


feign:
#  hystrix:
#    enabled: false #全局禁用Hystrix
  compression:
    request:
      enabled: true #对请求进行GZIP压缩，减少通信过程中的性能损耗
      mime-types: text/xml,application/xml,application/json #开启压缩可以有效节约网络资源，但是会增加CPU压力，建议把最小压缩的文档大小适度调大一点
      min-request-size: 2048
    response:
      enabled: true #对响应进行GZIP压缩，减少通信过程中的性能损耗

logging:
  level:
    com:
      define:
        service:
          SchedualService: DEBUG



