#发现6666是谷歌的非安全端口，所以所有端口改成9开头，四位的，防止因为使用到非安全端口，导致无法使用
server:
  port: 9878

spring:
  application:
    name: service-feign
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/

